# Related resources {#sec-apx-related-resources}

## Overview

This chapter provides links to several related resources from the Bioconductor and other communities.


## Data preprocessing procedures for the Visium platform

Data preprocessing procedures for spatial transcriptomics data from the 10x Genomics Visium platform:

- [**Visium data preprocessing**](https://lmweber.org/Visium-data-preprocessing/): Online book containing details on data preprocessing procedures for spatial transcriptomics data from the 10x Genomics Visium platform, using tools outside R and Bioconductor.


## Resources for other spatial omics platforms

Workflows and other resources for other spatial omics platforms:

- [**Analysis workflow for IMC data**](https://bodenmillergroup.github.io/IMCDataAnalysis/): Online book providing a workflow highlighting the use of common R/Bioconductor packages to analyze single-cell data obtained from segmented imaging mass cytometry (IMC) images. Examples focus on IMC data and can also be applied to images obtained by other highly-multiplexed imaging technologies, e.g. CODEX, MIBI, and mIF.

- [**VectraPolarisData**](https://bioconductor.org/packages/VectraPolarisData): Bioconductor data package providing two multiplex single-cell imaging datasets collected on Vectra Polaris and Vectra 3 instruments.


## Data structures

Data structures for storing spatial transcriptomics and other spatial omics data that are widely used outside the Bioconductor framework:

- [**AnnData**](https://anndata.readthedocs.io/en/latest/): Python class for storing single-cell and spatial data in the [scverse](https://scverse.org/) framework.

- [**SpatialData**](https://spatialdata.scverse.org/en/latest/): Python class for storing data from spatial transcriptomics and other spatial omics platforms.


## Statistical concepts

- [**Modern Statistics for Modern Biology**](https://www.huber.embl.de//msmb/index.html): Online textbook on concepts in modern statistics for high-throughput and high-dimensional biology, including [chapter on image data and spatial statistics](https://www.huber.embl.de//msmb/Chap-Images.html).
