# Preamble {-}

```{r "intro"}
#| echo: false
intro <- tryCatch(
    {
        description <- packageDescription("OSTA")
        pkg <- description$Package
        version <- description$Version
        license <- description$License
        glue::glue(
            "**Package:** {pkg}<br/>\n", 
            "**Compiled:** {as.character(Sys.Date())}<br/>\n", 
            "**Package version:** {version}<br/>\n", 
            "**R version:** {R.version.string}<br/>\n", 
            "**Bioconductor version:** {BiocManager::version()}<br/>\n", 
            "**License:** {license}<br/>"
        )
    }, 
    error = function(e) {"Local preview"}
)
```

`r intro`


## Docker image {-}

A `Docker` image built from this repository is available here: [ghcr.io/lmweber/osta](https://ghcr.io/lmweber/osta)

::: {.callout-tip icon='true'}
## Get started now

You can get access to all the packages used in this book in <1 minute, using this command in a terminal:

```{sh "docker", filename="bash"}
#| eval: false
docker run -it ghcr.io/lmweber/osta:devel R
```

:::


## RStudio Server {-}

An RStudio Server instance can be initiated from the `Docker` image as follows:

```{sh "rstudio", filename="bash"}
#| eval: false
docker run \
    --volume <local_folder>:<destination_folder> \
    -e PASSWORD=OHCA \
    -p 8787:8787 \
    ghcr.io/lmweber/osta:devel
```

The initiated RStudio Server instance will be available at: [https://localhost:8787](https://localhost:8787)


## BiocBook

This book is built using the [BiocBook](https://github.com/js2264/BiocBook) package, developed by [Jacques Serizay](https://jserizay.com/) for building Quarto books with Bioconductor.

More details on how to build a book using BiocBook can be found in the [BiocBook book](https://jserizay.com/BiocBookDemo/devel/).


## Session info {-}

::: {.callout-note collapse="true"}

## Click to expand

```{r "session info"}
#| cache: false
sessioninfo::session_info(
    installed.packages()[,"Package"], 
    include_base = TRUE
)
```

:::
