# Related resources {#sec-related-resources}


## Overview

In this chapter, we highlight several related resources from the Bioconductor and other communities.



## Data preprocessing procedures for Visium

[**Visium data preprocessing**](https://lmweber.org/Visium-data-preprocessing/)

- Online book containing details on data preprocessing procedures for spatially-resolved transcriptomics data from the 10x Genomics Visium platform (using tools outside R and Bioconductor).



## Resources for other spatial platforms

Workflows and other resources for other spatially-resolved platforms:

[**Analysis workflow for IMC data**](https://bodenmillergroup.github.io/IMCDataAnalysis/)

- Online book providing a workflow highlighting the use of common R/Bioconductor packages to analyze single-cell data obtained from segmented imaging mass cytometry (IMC) images. Examples focus on IMC data and can also be applied to images obtained by other highly-multiplexed imaging technologies, e.g. CODEX, MIBI, and mIF.

[**VectraPolarisData**](https://bioconductor.org/packages/VectraPolarisData)

- Bioconductor data package providing two multiplex single-cell imaging datasets collected on Vectra Polaris and Vectra 3 instruments.



## Data structures

Data structures for storing spatially-resolved transcriptomics (SRT) data.

[**SpatialExperiment**](https://bioconductor.org/packages/SpatialExperiment)

- Class for storing SRT data, which is used as the basis for the examples in this book [@Righelli2022]. See @sec-bioconductor-data-classes.

[**MoleculeExperiment**](https://bioconductor.org/packages/MoleculeExperiment)

- Class extending `SpatialExperiment` to store molecule-based SRT data within the R/Bioconductor framework [@PetersCouto2023]. See @sec-bioconductor-data-classes.

[**SpatialFeatureExperiment**](https://bioconductor.org/packages/SpatialFeatureExperiment)

- Class extending `SpatialExperiment` to store molecule-based SRT data within the R/Bioconductor framework [@Moses2023]. See @sec-bioconductor-data-classes.

[**AnnData**](https://anndata.readthedocs.io/en/latest/)

- Python class for storing single-cell and spatial data within the [scverse](https://scverse.org/) framework.

[**SpatialData**](https://spatialdata.scverse.org/en/latest/)

- Python class for storing spatial data from SRT and other platforms.



## Statistical concepts

[**Modern Statistics for Modern Biology**](https://www.huber.embl.de//msmb/index.html)

- Online textbook on concepts in modern statistics for high-throughput and high-dimensional biology, including [chapter on image data and spatial statistics](https://www.huber.embl.de//msmb/Chap-Images.html).
