```{r "welcome"}
#| echo: false
welcome <- tryCatch(
    {
        date <- format(Sys.time(), "%B %e, %Y")
        glue::glue(
            "**Published:** {date}<br/>"
        )
    }, 
    error = function(e) {"Local preview"}
)
```

`r welcome`


# Welcome {-}

This is the website for the online book **'Principles of Spatial Transcriptomics Analysis with Bioconductor'**.

This book provides discussion and interactive examples on computational analysis workflows for spatial transcriptomics data, using [Bioconductor](http://bioconductor.org/) in R. The chapters contain details on individual analysis steps and longer workflows, with interactive examples consisting of R code and example datasets.

The book is organized into several parts, including introductory materials, analysis steps, and extended workflows, for sequencing-based and imaging-based spatial transcriptomics platforms.

Additional details on analysis workflows for non-spatial single-cell data as well as further introductory materials on R and Bioconductor can be found in the related book [Orchestrating Single-Cell Analysis with Bioconductor (OSCA)](https://bioconductor.org/books/release/OSCA/).
